language: ruby

before_install:
  # Workaround for https://github.com/travis-ci/travis-ci/issues/8969
  - gem update --system

rvm:
  - 2.4
  - 2.5
  - 2.6

env:
  - RAILS_VERSION=5.1
  - RAILS_VERSION=5.2
  - RAILS_VERSION=6.0

matrix:
  exclude:
    - rvm: 2.5
      env: RAILS_VERSION=4.2
    - rvm: 2.5
      env: RAILS_VERSION=5.0
    - rvm: 2.6
      env: RAILS_VERSION=4.2
    - rvm: 2.6
      env: RAILS_VERSION=5.0

sudo: false
